# Generated by Django 2.0.5 on 2018-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('待定', '待定'), ('工讀', '工讀'), ('約聘', '約聘'), ('正職', '正職'), ('顧問', '顧問'), ('留職停薪', '留職停薪')], default='待定', max_length=10),
        ),
    ]
