# Generated by Django 2.0.5 on 2018-05-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0009_auto_20180517_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrospective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wentwell_myself', models.TextField()),
                ('wentwell_review', models.TextField()),
                ('wentwell_approval', models.TextField()),
                ('improve_myself', models.TextField()),
                ('improve_review', models.TextField()),
                ('improve_approval', models.TextField()),
                ('support', models.CharField(max_length=100)),
                ('support_reason', models.TextField()),
                ('inspire', models.CharField(max_length=100)),
                ('inspire_reason', models.TextField()),
                ('metrics', models.TextField()),
                ('myself_score', models.CharField(choices=[('0', '0'), ('0.1', '0.1'), ('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5'), ('0.6', '0.6'), ('0.7', '0.7'), ('0.8', '0.8'), ('0.9', '0.9'), ('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('2.0', '2.0')], default='0.0', max_length=10)),
                ('reviewer_score', models.CharField(choices=[('0', '0'), ('0.1', '0.1'), ('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5'), ('0.6', '0.6'), ('0.7', '0.7'), ('0.8', '0.8'), ('0.9', '0.9'), ('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('2.0', '2.0')], default='0.0', max_length=10)),
                ('approval_score', models.CharField(choices=[('0', '0'), ('0.1', '0.1'), ('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5'), ('0.6', '0.6'), ('0.7', '0.7'), ('0.8', '0.8'), ('0.9', '0.9'), ('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.5', '1.5'), ('1.6', '1.6'), ('1.7', '1.7'), ('1.8', '1.8'), ('1.9', '1.9'), ('2.0', '2.0')], default='0.0', max_length=10)),
                ('current_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='kpi.Duration')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='kpi.Employee')),
            ],
        ),
    ]
