# Generated by Django 2.0.5 on 2018-05-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0010_retrospective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duration',
            old_name='star_date',
            new_name='start_date',
        ),
    ]
