# Generated by Django 2.0.5 on 2018-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0011_auto_20180517_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrospective',
            name='approval_score',
        ),
        migrations.RemoveField(
            model_name='retrospective',
            name='myself_score',
        ),
        migrations.RemoveField(
            model_name='retrospective',
            name='reviewer_score',
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='inspire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='support',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
