# Generated by Django 2.0.5 on 2018-05-22 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0012_auto_20180518_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('comment', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('自評', '自評'), ('邀請評分', '邀請評分'), ('諮詢', '諮詢'), ('主管評分', '主管評分'), ('核准', '核准')], default='不明', max_length=30)),
                ('done', models.BooleanField(default=0)),
                ('eval_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='kpi.Employee')),
            ],
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='improve_approval',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='improve_myself',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='improve_review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='inspire_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='metrics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='support_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='wentwell_approval',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='wentwell_myself',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='retrospective',
            name='wentwell_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='retro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='kpi.Retrospective'),
        ),
    ]
