# Generated by Django 2.0.5 on 2018-05-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0013_auto_20180522_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
